# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ed49ae2daee8f31b94d5143398fddc89e4af6ffb3b2fb1676ec49f15e0f0993987431153c7154308a3f9f244cefe720fe8fdb1b9adf8a8cf16c67523e010c4b

test:
  secret_key_base: 2ec247617cd4f55bd17e08b2a0e2d3f6e2d0a4220c9467019ab2190d0613dc1c87d35c95c37b6d51f4444af4ae5b20a98ac4bd997fbd68c31f895c41fad21f25

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
